import type { MigrationBuilder } from 'node-pg-migrate';

// FK-critical reference data. `product_category` is referenced NOT NULL by `product`,
// `product_concept`, and `invoice_line`; `country`/`country_subdivision` back onboarding
// region selection. The tables are created by earlier migrations but were previously only
// populated by the local-only `seed:local` script, so deployed stages (which run
// `migrate:up` but never the seed) had empty tables and every ingestion product insert
// failed the `product_category` FK. Seeding here puts the data on the deploy path for
// every environment.
//
// The rows are an immutable point-in-time snapshot, mirroring src/local/seeds/
// (product-taxonomy.ts, country-subdivisions.ts). Migrations are self-contained and must
// not import mutable app code; later additions land in their own follow-up migration.
// Inserts are idempotent (ON CONFLICT DO NOTHING) so this overlaps harmlessly with
// seed:local and is safe to re-run.

export interface CategoryRow { id: string; parentId: string | null; name: string; nameNl: string; level: number; }
export interface CountryRow { code: string; name: string; }
export interface SubdivisionRow { code: string; countryCode: string; name: string; }

// Exported so the parity test can assert this snapshot stays in sync with src/local/seeds/*
// and covers the backend category validator (CATEGORY_TAXONOMY); see
// test/seed_reference_data.test.ts. Drift in any of the three copies fails the build.
//
// Macro categories precede their sub-categories so the self-referential parent_id FK is
// satisfied on insert.
export const CATEGORIES: CategoryRow[] = [
  { id: 'cat-groceries', parentId: null, name: 'Groceries', nameNl: 'Boodschappen', level: 1 },
  { id: 'cat-household', parentId: null, name: 'Household', nameNl: 'Huishouden', level: 1 },
  { id: 'cat-personal-care', parentId: null, name: 'Personal Care & Pharmacy', nameNl: 'Persoonlijke verzorging', level: 1 },
  { id: 'cat-baby', parentId: null, name: 'Baby & Kids', nameNl: 'Baby & Kids', level: 1 },
  { id: 'cat-pet', parentId: null, name: 'Pet', nameNl: 'Huisdier', level: 1 },
  { id: 'cat-dining-out', parentId: null, name: 'Dining Out', nameNl: 'Uit eten', level: 1 },
  { id: 'cat-transport', parentId: null, name: 'Transport & Fuel', nameNl: 'Transport & Brandstof', level: 1 },
  { id: 'cat-clothing', parentId: null, name: 'Clothing', nameNl: 'Kleding', level: 1 },
  { id: 'cat-electronics', parentId: null, name: 'Electronics', nameNl: 'Elektronica', level: 1 },
  { id: 'cat-health', parentId: null, name: 'Health', nameNl: 'Gezondheid', level: 1 },
  { id: 'cat-home-garden', parentId: null, name: 'Home & Garden', nameNl: 'Huis & Tuin', level: 1 },
  { id: 'cat-entertainment', parentId: null, name: 'Entertainment', nameNl: 'Entertainment', level: 1 },
  { id: 'cat-services', parentId: null, name: 'Services', nameNl: 'Diensten', level: 1 },
  { id: 'cat-other', parentId: null, name: 'Other', nameNl: 'Overig', level: 1 },
  { id: 'cat-dairy', parentId: 'cat-groceries', name: 'Dairy & Eggs', nameNl: 'Zuivel & Eieren', level: 2 },
  { id: 'cat-produce', parentId: 'cat-groceries', name: 'Produce', nameNl: 'Groente & Fruit', level: 2 },
  { id: 'cat-meat-fish', parentId: 'cat-groceries', name: 'Meat & Fish', nameNl: 'Vlees & Vis', level: 2 },
  { id: 'cat-bakery', parentId: 'cat-groceries', name: 'Bakery', nameNl: 'Bakkerij', level: 2 },
  { id: 'cat-pantry', parentId: 'cat-groceries', name: 'Pantry', nameNl: 'Droogwaren', level: 2 },
  { id: 'cat-frozen', parentId: 'cat-groceries', name: 'Frozen', nameNl: 'Diepvries', level: 2 },
  { id: 'cat-beverages', parentId: 'cat-groceries', name: 'Beverages', nameNl: 'Dranken', level: 2 },
  { id: 'cat-alcohol', parentId: 'cat-groceries', name: 'Alcohol', nameNl: 'Alcohol', level: 2 },
  { id: 'cat-snacks', parentId: 'cat-groceries', name: 'Snacks & Sweets', nameNl: 'Snacks & Snoep', level: 2 },
  { id: 'cat-pharmacy', parentId: 'cat-personal-care', name: 'Pharmacy', nameNl: 'Apotheek', level: 2 },
];

export const COUNTRIES: CountryRow[] = [
  // The four UK nations are modelled as separate top-level countries (no ISO
  // 3166-1 alpha-2 exists for them, so EN/SC/WA/NI are project-local codes that
  // fit the CHAR(2) `country.code`). Their regions live under EN-/SC-/WA-/NI-.
  { code: 'EN', name: 'England' },
  { code: 'SC', name: 'Scotland' },
  { code: 'WA', name: 'Wales' },
  { code: 'NI', name: 'Northern Ireland' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'US', name: 'United States' },
  { code: 'IT', name: 'Italy' },
  { code: 'PT', name: 'Portugal' },
  { code: 'ES', name: 'Spain' },
  { code: 'CA', name: 'Canada' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CN', name: 'China' },
  { code: 'AT', name: 'Austria' },
  { code: 'DK', name: 'Denmark' },
];

export const SUBDIVISIONS: SubdivisionRow[] = [
  { code: 'EN-NE', countryCode: 'EN', name: 'North East' },
  { code: 'EN-NW', countryCode: 'EN', name: 'North West' },
  { code: 'EN-YH', countryCode: 'EN', name: 'Yorkshire and the Humber' },
  { code: 'EN-EM', countryCode: 'EN', name: 'East Midlands' },
  { code: 'EN-WM', countryCode: 'EN', name: 'West Midlands' },
  { code: 'EN-EE', countryCode: 'EN', name: 'East of England' },
  { code: 'EN-LDN', countryCode: 'EN', name: 'London' },
  { code: 'EN-SE', countryCode: 'EN', name: 'South East' },
  { code: 'EN-SW', countryCode: 'EN', name: 'South West' },
  { code: 'SC-ABE', countryCode: 'SC', name: 'Aberdeen City' },
  { code: 'SC-ABD', countryCode: 'SC', name: 'Aberdeenshire' },
  { code: 'SC-ANS', countryCode: 'SC', name: 'Angus' },
  { code: 'SC-AGB', countryCode: 'SC', name: 'Argyll and Bute' },
  { code: 'SC-CLK', countryCode: 'SC', name: 'Clackmannanshire' },
  { code: 'SC-DGY', countryCode: 'SC', name: 'Dumfries and Galloway' },
  { code: 'SC-DND', countryCode: 'SC', name: 'Dundee City' },
  { code: 'SC-EAY', countryCode: 'SC', name: 'East Ayrshire' },
  { code: 'SC-EDU', countryCode: 'SC', name: 'East Dunbartonshire' },
  { code: 'SC-ELN', countryCode: 'SC', name: 'East Lothian' },
  { code: 'SC-ERW', countryCode: 'SC', name: 'East Renfrewshire' },
  { code: 'SC-EDH', countryCode: 'SC', name: 'City of Edinburgh' },
  { code: 'SC-ELS', countryCode: 'SC', name: 'Na h-Eileanan Siar' },
  { code: 'SC-FAL', countryCode: 'SC', name: 'Falkirk' },
  { code: 'SC-FIF', countryCode: 'SC', name: 'Fife' },
  { code: 'SC-GLG', countryCode: 'SC', name: 'Glasgow City' },
  { code: 'SC-HLD', countryCode: 'SC', name: 'Highland' },
  { code: 'SC-IVC', countryCode: 'SC', name: 'Inverclyde' },
  { code: 'SC-MLN', countryCode: 'SC', name: 'Midlothian' },
  { code: 'SC-MRY', countryCode: 'SC', name: 'Moray' },
  { code: 'SC-NAY', countryCode: 'SC', name: 'North Ayrshire' },
  { code: 'SC-NLK', countryCode: 'SC', name: 'North Lanarkshire' },
  { code: 'SC-ORK', countryCode: 'SC', name: 'Orkney Islands' },
  { code: 'SC-PKN', countryCode: 'SC', name: 'Perth and Kinross' },
  { code: 'SC-RFW', countryCode: 'SC', name: 'Renfrewshire' },
  { code: 'SC-SCB', countryCode: 'SC', name: 'Scottish Borders' },
  { code: 'SC-ZET', countryCode: 'SC', name: 'Shetland Islands' },
  { code: 'SC-SAY', countryCode: 'SC', name: 'South Ayrshire' },
  { code: 'SC-SLK', countryCode: 'SC', name: 'South Lanarkshire' },
  { code: 'SC-STG', countryCode: 'SC', name: 'Stirling' },
  { code: 'SC-WDU', countryCode: 'SC', name: 'West Dunbartonshire' },
  { code: 'SC-WLN', countryCode: 'SC', name: 'West Lothian' },
  { code: 'WA-BGW', countryCode: 'WA', name: 'Blaenau Gwent' },
  { code: 'WA-BGE', countryCode: 'WA', name: 'Bridgend' },
  { code: 'WA-CAY', countryCode: 'WA', name: 'Caerphilly' },
  { code: 'WA-CRF', countryCode: 'WA', name: 'Cardiff' },
  { code: 'WA-CMN', countryCode: 'WA', name: 'Carmarthenshire' },
  { code: 'WA-CGN', countryCode: 'WA', name: 'Ceredigion' },
  { code: 'WA-CWY', countryCode: 'WA', name: 'Conwy' },
  { code: 'WA-DEN', countryCode: 'WA', name: 'Denbighshire' },
  { code: 'WA-FLN', countryCode: 'WA', name: 'Flintshire' },
  { code: 'WA-GWN', countryCode: 'WA', name: 'Gwynedd' },
  { code: 'WA-AGY', countryCode: 'WA', name: 'Isle of Anglesey' },
  { code: 'WA-MTY', countryCode: 'WA', name: 'Merthyr Tydfil' },
  { code: 'WA-MON', countryCode: 'WA', name: 'Monmouthshire' },
  { code: 'WA-NTL', countryCode: 'WA', name: 'Neath Port Talbot' },
  { code: 'WA-NWP', countryCode: 'WA', name: 'Newport' },
  { code: 'WA-PEM', countryCode: 'WA', name: 'Pembrokeshire' },
  { code: 'WA-POW', countryCode: 'WA', name: 'Powys' },
  { code: 'WA-RCT', countryCode: 'WA', name: 'Rhondda Cynon Taf' },
  { code: 'WA-SWA', countryCode: 'WA', name: 'Swansea' },
  { code: 'WA-TOF', countryCode: 'WA', name: 'Torfaen' },
  { code: 'WA-VGL', countryCode: 'WA', name: 'Vale of Glamorgan' },
  { code: 'WA-WRX', countryCode: 'WA', name: 'Wrexham' },
  { code: 'NI-ANN', countryCode: 'NI', name: 'Antrim and Newtownabbey' },
  { code: 'NI-AND', countryCode: 'NI', name: 'Ards and North Down' },
  { code: 'NI-ABC', countryCode: 'NI', name: 'Armagh City, Banbridge and Craigavon' },
  { code: 'NI-BFS', countryCode: 'NI', name: 'Belfast' },
  { code: 'NI-CCG', countryCode: 'NI', name: 'Causeway Coast and Glens' },
  { code: 'NI-DRS', countryCode: 'NI', name: 'Derry City and Strabane' },
  { code: 'NI-FMO', countryCode: 'NI', name: 'Fermanagh and Omagh' },
  { code: 'NI-LBC', countryCode: 'NI', name: 'Lisburn and Castlereagh' },
  { code: 'NI-MEA', countryCode: 'NI', name: 'Mid and East Antrim' },
  { code: 'NI-MUL', countryCode: 'NI', name: 'Mid Ulster' },
  { code: 'NI-NMD', countryCode: 'NI', name: 'Newry, Mourne and Down' },
  { code: 'NL-DR', countryCode: 'NL', name: 'Drenthe' },
  { code: 'NL-FL', countryCode: 'NL', name: 'Flevoland' },
  { code: 'NL-FR', countryCode: 'NL', name: 'Friesland' },
  { code: 'NL-GE', countryCode: 'NL', name: 'Gelderland' },
  { code: 'NL-GR', countryCode: 'NL', name: 'Groningen' },
  { code: 'NL-LI', countryCode: 'NL', name: 'Limburg' },
  { code: 'NL-NB', countryCode: 'NL', name: 'Noord-Brabant' },
  { code: 'NL-NH', countryCode: 'NL', name: 'Noord-Holland' },
  { code: 'NL-OV', countryCode: 'NL', name: 'Overijssel' },
  { code: 'NL-UT', countryCode: 'NL', name: 'Utrecht' },
  { code: 'NL-ZE', countryCode: 'NL', name: 'Zeeland' },
  { code: 'NL-ZH', countryCode: 'NL', name: 'Zuid-Holland' },
  { code: 'FR-ARA', countryCode: 'FR', name: 'Auvergne-Rhône-Alpes' },
  { code: 'FR-BFC', countryCode: 'FR', name: 'Bourgogne-Franche-Comté' },
  { code: 'FR-BRE', countryCode: 'FR', name: 'Bretagne' },
  { code: 'FR-CVL', countryCode: 'FR', name: 'Centre-Val de Loire' },
  { code: 'FR-COR', countryCode: 'FR', name: 'Corse' },
  { code: 'FR-GES', countryCode: 'FR', name: 'Grand Est' },
  { code: 'FR-HDF', countryCode: 'FR', name: 'Hauts-de-France' },
  { code: 'FR-IDF', countryCode: 'FR', name: 'Île-de-France' },
  { code: 'FR-NOR', countryCode: 'FR', name: 'Normandie' },
  { code: 'FR-NAQ', countryCode: 'FR', name: 'Nouvelle-Aquitaine' },
  { code: 'FR-OCC', countryCode: 'FR', name: 'Occitanie' },
  { code: 'FR-PDL', countryCode: 'FR', name: 'Pays de la Loire' },
  { code: 'FR-PAC', countryCode: 'FR', name: "Provence-Alpes-Côte d'Azur" },
  { code: 'FR-GP', countryCode: 'FR', name: 'Guadeloupe' },
  { code: 'FR-MQ', countryCode: 'FR', name: 'Martinique' },
  { code: 'FR-GF', countryCode: 'FR', name: 'Guyane' },
  { code: 'FR-RE', countryCode: 'FR', name: 'La Réunion' },
  { code: 'FR-YT', countryCode: 'FR', name: 'Mayotte' },
  { code: 'DE-BW', countryCode: 'DE', name: 'Baden-Württemberg' },
  { code: 'DE-BY', countryCode: 'DE', name: 'Bayern' },
  { code: 'DE-BE', countryCode: 'DE', name: 'Berlin' },
  { code: 'DE-BB', countryCode: 'DE', name: 'Brandenburg' },
  { code: 'DE-HB', countryCode: 'DE', name: 'Bremen' },
  { code: 'DE-HH', countryCode: 'DE', name: 'Hamburg' },
  { code: 'DE-HE', countryCode: 'DE', name: 'Hessen' },
  { code: 'DE-MV', countryCode: 'DE', name: 'Mecklenburg-Vorpommern' },
  { code: 'DE-NI', countryCode: 'DE', name: 'Niedersachsen' },
  { code: 'DE-NW', countryCode: 'DE', name: 'Nordrhein-Westfalen' },
  { code: 'DE-RP', countryCode: 'DE', name: 'Rheinland-Pfalz' },
  { code: 'DE-SL', countryCode: 'DE', name: 'Saarland' },
  { code: 'DE-SN', countryCode: 'DE', name: 'Sachsen' },
  { code: 'DE-ST', countryCode: 'DE', name: 'Sachsen-Anhalt' },
  { code: 'DE-SH', countryCode: 'DE', name: 'Schleswig-Holstein' },
  { code: 'DE-TH', countryCode: 'DE', name: 'Thüringen' },
  { code: 'US-AL', countryCode: 'US', name: 'Alabama' },
  { code: 'US-AK', countryCode: 'US', name: 'Alaska' },
  { code: 'US-AZ', countryCode: 'US', name: 'Arizona' },
  { code: 'US-AR', countryCode: 'US', name: 'Arkansas' },
  { code: 'US-CA', countryCode: 'US', name: 'California' },
  { code: 'US-CO', countryCode: 'US', name: 'Colorado' },
  { code: 'US-CT', countryCode: 'US', name: 'Connecticut' },
  { code: 'US-DE', countryCode: 'US', name: 'Delaware' },
  { code: 'US-FL', countryCode: 'US', name: 'Florida' },
  { code: 'US-GA', countryCode: 'US', name: 'Georgia' },
  { code: 'US-HI', countryCode: 'US', name: 'Hawaii' },
  { code: 'US-ID', countryCode: 'US', name: 'Idaho' },
  { code: 'US-IL', countryCode: 'US', name: 'Illinois' },
  { code: 'US-IN', countryCode: 'US', name: 'Indiana' },
  { code: 'US-IA', countryCode: 'US', name: 'Iowa' },
  { code: 'US-KS', countryCode: 'US', name: 'Kansas' },
  { code: 'US-KY', countryCode: 'US', name: 'Kentucky' },
  { code: 'US-LA', countryCode: 'US', name: 'Louisiana' },
  { code: 'US-ME', countryCode: 'US', name: 'Maine' },
  { code: 'US-MD', countryCode: 'US', name: 'Maryland' },
  { code: 'US-MA', countryCode: 'US', name: 'Massachusetts' },
  { code: 'US-MI', countryCode: 'US', name: 'Michigan' },
  { code: 'US-MN', countryCode: 'US', name: 'Minnesota' },
  { code: 'US-MS', countryCode: 'US', name: 'Mississippi' },
  { code: 'US-MO', countryCode: 'US', name: 'Missouri' },
  { code: 'US-MT', countryCode: 'US', name: 'Montana' },
  { code: 'US-NE', countryCode: 'US', name: 'Nebraska' },
  { code: 'US-NV', countryCode: 'US', name: 'Nevada' },
  { code: 'US-NH', countryCode: 'US', name: 'New Hampshire' },
  { code: 'US-NJ', countryCode: 'US', name: 'New Jersey' },
  { code: 'US-NM', countryCode: 'US', name: 'New Mexico' },
  { code: 'US-NY', countryCode: 'US', name: 'New York' },
  { code: 'US-NC', countryCode: 'US', name: 'North Carolina' },
  { code: 'US-ND', countryCode: 'US', name: 'North Dakota' },
  { code: 'US-OH', countryCode: 'US', name: 'Ohio' },
  { code: 'US-OK', countryCode: 'US', name: 'Oklahoma' },
  { code: 'US-OR', countryCode: 'US', name: 'Oregon' },
  { code: 'US-PA', countryCode: 'US', name: 'Pennsylvania' },
  { code: 'US-RI', countryCode: 'US', name: 'Rhode Island' },
  { code: 'US-SC', countryCode: 'US', name: 'South Carolina' },
  { code: 'US-SD', countryCode: 'US', name: 'South Dakota' },
  { code: 'US-TN', countryCode: 'US', name: 'Tennessee' },
  { code: 'US-TX', countryCode: 'US', name: 'Texas' },
  { code: 'US-UT', countryCode: 'US', name: 'Utah' },
  { code: 'US-VT', countryCode: 'US', name: 'Vermont' },
  { code: 'US-VA', countryCode: 'US', name: 'Virginia' },
  { code: 'US-WA', countryCode: 'US', name: 'Washington' },
  { code: 'US-WV', countryCode: 'US', name: 'West Virginia' },
  { code: 'US-WI', countryCode: 'US', name: 'Wisconsin' },
  { code: 'US-WY', countryCode: 'US', name: 'Wyoming' },
  { code: 'US-DC', countryCode: 'US', name: 'District of Columbia' },
  { code: 'IT-65', countryCode: 'IT', name: 'Abruzzo' },
  { code: 'IT-77', countryCode: 'IT', name: 'Basilicata' },
  { code: 'IT-78', countryCode: 'IT', name: 'Calabria' },
  { code: 'IT-72', countryCode: 'IT', name: 'Campania' },
  { code: 'IT-45', countryCode: 'IT', name: 'Emilia-Romagna' },
  { code: 'IT-36', countryCode: 'IT', name: 'Friuli Venezia Giulia' },
  { code: 'IT-62', countryCode: 'IT', name: 'Lazio' },
  { code: 'IT-42', countryCode: 'IT', name: 'Liguria' },
  { code: 'IT-25', countryCode: 'IT', name: 'Lombardia' },
  { code: 'IT-57', countryCode: 'IT', name: 'Marche' },
  { code: 'IT-67', countryCode: 'IT', name: 'Molise' },
  { code: 'IT-21', countryCode: 'IT', name: 'Piemonte' },
  { code: 'IT-75', countryCode: 'IT', name: 'Puglia' },
  { code: 'IT-88', countryCode: 'IT', name: 'Sardegna' },
  { code: 'IT-82', countryCode: 'IT', name: 'Sicilia' },
  { code: 'IT-52', countryCode: 'IT', name: 'Toscana' },
  { code: 'IT-32', countryCode: 'IT', name: 'Trentino-Alto Adige' },
  { code: 'IT-55', countryCode: 'IT', name: 'Umbria' },
  { code: 'IT-23', countryCode: 'IT', name: "Valle d'Aosta" },
  { code: 'IT-34', countryCode: 'IT', name: 'Veneto' },
  { code: 'PT-01', countryCode: 'PT', name: 'Aveiro' },
  { code: 'PT-02', countryCode: 'PT', name: 'Beja' },
  { code: 'PT-03', countryCode: 'PT', name: 'Braga' },
  { code: 'PT-04', countryCode: 'PT', name: 'Bragança' },
  { code: 'PT-05', countryCode: 'PT', name: 'Castelo Branco' },
  { code: 'PT-06', countryCode: 'PT', name: 'Coimbra' },
  { code: 'PT-07', countryCode: 'PT', name: 'Évora' },
  { code: 'PT-08', countryCode: 'PT', name: 'Faro' },
  { code: 'PT-09', countryCode: 'PT', name: 'Guarda' },
  { code: 'PT-10', countryCode: 'PT', name: 'Leiria' },
  { code: 'PT-11', countryCode: 'PT', name: 'Lisboa' },
  { code: 'PT-12', countryCode: 'PT', name: 'Portalegre' },
  { code: 'PT-13', countryCode: 'PT', name: 'Porto' },
  { code: 'PT-14', countryCode: 'PT', name: 'Santarém' },
  { code: 'PT-15', countryCode: 'PT', name: 'Setúbal' },
  { code: 'PT-16', countryCode: 'PT', name: 'Viana do Castelo' },
  { code: 'PT-17', countryCode: 'PT', name: 'Vila Real' },
  { code: 'PT-18', countryCode: 'PT', name: 'Viseu' },
  { code: 'PT-20', countryCode: 'PT', name: 'Região Autónoma dos Açores' },
  { code: 'PT-30', countryCode: 'PT', name: 'Região Autónoma da Madeira' },
  { code: 'ES-AN', countryCode: 'ES', name: 'Andalucía' },
  { code: 'ES-AR', countryCode: 'ES', name: 'Aragón' },
  { code: 'ES-AS', countryCode: 'ES', name: 'Asturias' },
  { code: 'ES-CB', countryCode: 'ES', name: 'Cantabria' },
  { code: 'ES-CL', countryCode: 'ES', name: 'Castilla y León' },
  { code: 'ES-CM', countryCode: 'ES', name: 'Castilla-La Mancha' },
  { code: 'ES-CT', countryCode: 'ES', name: 'Cataluña' },
  { code: 'ES-EX', countryCode: 'ES', name: 'Extremadura' },
  { code: 'ES-GA', countryCode: 'ES', name: 'Galicia' },
  { code: 'ES-IB', countryCode: 'ES', name: 'Illes Balears' },
  { code: 'ES-CN', countryCode: 'ES', name: 'Canarias' },
  { code: 'ES-RI', countryCode: 'ES', name: 'La Rioja' },
  { code: 'ES-MD', countryCode: 'ES', name: 'Madrid' },
  { code: 'ES-MC', countryCode: 'ES', name: 'Murcia' },
  { code: 'ES-NC', countryCode: 'ES', name: 'Navarra' },
  { code: 'ES-PV', countryCode: 'ES', name: 'País Vasco' },
  { code: 'ES-VC', countryCode: 'ES', name: 'Comunidad Valenciana' },
  { code: 'ES-CE', countryCode: 'ES', name: 'Ceuta' },
  { code: 'ES-ML', countryCode: 'ES', name: 'Melilla' },
  { code: 'CA-AB', countryCode: 'CA', name: 'Alberta' },
  { code: 'CA-BC', countryCode: 'CA', name: 'British Columbia' },
  { code: 'CA-MB', countryCode: 'CA', name: 'Manitoba' },
  { code: 'CA-NB', countryCode: 'CA', name: 'New Brunswick' },
  { code: 'CA-NL', countryCode: 'CA', name: 'Newfoundland and Labrador' },
  { code: 'CA-NS', countryCode: 'CA', name: 'Nova Scotia' },
  { code: 'CA-ON', countryCode: 'CA', name: 'Ontario' },
  { code: 'CA-PE', countryCode: 'CA', name: 'Prince Edward Island' },
  { code: 'CA-QC', countryCode: 'CA', name: 'Quebec' },
  { code: 'CA-SK', countryCode: 'CA', name: 'Saskatchewan' },
  { code: 'CA-NT', countryCode: 'CA', name: 'Northwest Territories' },
  { code: 'CA-NU', countryCode: 'CA', name: 'Nunavut' },
  { code: 'CA-YT', countryCode: 'CA', name: 'Yukon' },
  { code: 'BR-AC', countryCode: 'BR', name: 'Acre' },
  { code: 'BR-AL', countryCode: 'BR', name: 'Alagoas' },
  { code: 'BR-AP', countryCode: 'BR', name: 'Amapá' },
  { code: 'BR-AM', countryCode: 'BR', name: 'Amazonas' },
  { code: 'BR-BA', countryCode: 'BR', name: 'Bahia' },
  { code: 'BR-CE', countryCode: 'BR', name: 'Ceará' },
  { code: 'BR-DF', countryCode: 'BR', name: 'Distrito Federal' },
  { code: 'BR-ES', countryCode: 'BR', name: 'Espírito Santo' },
  { code: 'BR-GO', countryCode: 'BR', name: 'Goiás' },
  { code: 'BR-MA', countryCode: 'BR', name: 'Maranhão' },
  { code: 'BR-MT', countryCode: 'BR', name: 'Mato Grosso' },
  { code: 'BR-MS', countryCode: 'BR', name: 'Mato Grosso do Sul' },
  { code: 'BR-MG', countryCode: 'BR', name: 'Minas Gerais' },
  { code: 'BR-PA', countryCode: 'BR', name: 'Pará' },
  { code: 'BR-PB', countryCode: 'BR', name: 'Paraíba' },
  { code: 'BR-PR', countryCode: 'BR', name: 'Paraná' },
  { code: 'BR-PE', countryCode: 'BR', name: 'Pernambuco' },
  { code: 'BR-PI', countryCode: 'BR', name: 'Piauí' },
  { code: 'BR-RJ', countryCode: 'BR', name: 'Rio de Janeiro' },
  { code: 'BR-RN', countryCode: 'BR', name: 'Rio Grande do Norte' },
  { code: 'BR-RS', countryCode: 'BR', name: 'Rio Grande do Sul' },
  { code: 'BR-RO', countryCode: 'BR', name: 'Rondônia' },
  { code: 'BR-RR', countryCode: 'BR', name: 'Roraima' },
  { code: 'BR-SC', countryCode: 'BR', name: 'Santa Catarina' },
  { code: 'BR-SP', countryCode: 'BR', name: 'São Paulo' },
  { code: 'BR-SE', countryCode: 'BR', name: 'Sergipe' },
  { code: 'BR-TO', countryCode: 'BR', name: 'Tocantins' },
  { code: 'CN-BJ', countryCode: 'CN', name: 'Beijing' },
  { code: 'CN-TJ', countryCode: 'CN', name: 'Tianjin' },
  { code: 'CN-HE', countryCode: 'CN', name: 'Hebei' },
  { code: 'CN-SX', countryCode: 'CN', name: 'Shanxi' },
  { code: 'CN-NM', countryCode: 'CN', name: 'Inner Mongolia' },
  { code: 'CN-LN', countryCode: 'CN', name: 'Liaoning' },
  { code: 'CN-JL', countryCode: 'CN', name: 'Jilin' },
  { code: 'CN-HL', countryCode: 'CN', name: 'Heilongjiang' },
  { code: 'CN-SH', countryCode: 'CN', name: 'Shanghai' },
  { code: 'CN-JS', countryCode: 'CN', name: 'Jiangsu' },
  { code: 'CN-ZJ', countryCode: 'CN', name: 'Zhejiang' },
  { code: 'CN-AH', countryCode: 'CN', name: 'Anhui' },
  { code: 'CN-FJ', countryCode: 'CN', name: 'Fujian' },
  { code: 'CN-JX', countryCode: 'CN', name: 'Jiangxi' },
  { code: 'CN-SD', countryCode: 'CN', name: 'Shandong' },
  { code: 'CN-HA', countryCode: 'CN', name: 'Henan' },
  { code: 'CN-HB', countryCode: 'CN', name: 'Hubei' },
  { code: 'CN-HN', countryCode: 'CN', name: 'Hunan' },
  { code: 'CN-GD', countryCode: 'CN', name: 'Guangdong' },
  { code: 'CN-GX', countryCode: 'CN', name: 'Guangxi' },
  { code: 'CN-HI', countryCode: 'CN', name: 'Hainan' },
  { code: 'CN-CQ', countryCode: 'CN', name: 'Chongqing' },
  { code: 'CN-SC', countryCode: 'CN', name: 'Sichuan' },
  { code: 'CN-GZ', countryCode: 'CN', name: 'Guizhou' },
  { code: 'CN-YN', countryCode: 'CN', name: 'Yunnan' },
  { code: 'CN-XZ', countryCode: 'CN', name: 'Tibet' },
  { code: 'CN-SN', countryCode: 'CN', name: 'Shaanxi' },
  { code: 'CN-GS', countryCode: 'CN', name: 'Gansu' },
  { code: 'CN-QH', countryCode: 'CN', name: 'Qinghai' },
  { code: 'CN-NX', countryCode: 'CN', name: 'Ningxia' },
  { code: 'CN-XJ', countryCode: 'CN', name: 'Xinjiang' },
  { code: 'CN-TW', countryCode: 'CN', name: 'Taiwan' },
  { code: 'CN-HK', countryCode: 'CN', name: 'Hong Kong' },
  { code: 'CN-MO', countryCode: 'CN', name: 'Macao' },
  { code: 'AT-1', countryCode: 'AT', name: 'Burgenland' },
  { code: 'AT-2', countryCode: 'AT', name: 'Kärnten' },
  { code: 'AT-3', countryCode: 'AT', name: 'Niederösterreich' },
  { code: 'AT-4', countryCode: 'AT', name: 'Oberösterreich' },
  { code: 'AT-5', countryCode: 'AT', name: 'Salzburg' },
  { code: 'AT-6', countryCode: 'AT', name: 'Steiermark' },
  { code: 'AT-7', countryCode: 'AT', name: 'Tirol' },
  { code: 'AT-8', countryCode: 'AT', name: 'Vorarlberg' },
  { code: 'AT-9', countryCode: 'AT', name: 'Wien' },
  { code: 'DK-84', countryCode: 'DK', name: 'Hovedstaden' },
  { code: 'DK-82', countryCode: 'DK', name: 'Midtjylland' },
  { code: 'DK-81', countryCode: 'DK', name: 'Nordjylland' },
  { code: 'DK-85', countryCode: 'DK', name: 'Sjælland' },
  { code: 'DK-83', countryCode: 'DK', name: 'Syddanmark' },
];

const sqlLiteral = (value: string | null): string =>
  value === null ? 'NULL' : `'${value.replace(/'/g, "''")}'`;

export async function up(pgm: MigrationBuilder): Promise<void> {
  const categories = CATEGORIES
    .map((c) => `(${sqlLiteral(c.id)}, ${sqlLiteral(c.parentId)}, ${sqlLiteral(c.name)}, ${sqlLiteral(c.nameNl)}, ${c.level})`)
    .join(',\n    ');
  pgm.sql(`
    INSERT INTO product_category (id, parent_id, name, name_nl, level) VALUES
    ${categories}
    ON CONFLICT (id) DO NOTHING;
  `);

  const countries = COUNTRIES
    .map((c) => `(${sqlLiteral(c.code)}, ${sqlLiteral(c.name)})`)
    .join(',\n    ');
  pgm.sql(`
    INSERT INTO country (code, name) VALUES
    ${countries}
    ON CONFLICT (code) DO NOTHING;
  `);

  const subdivisions = SUBDIVISIONS
    .map((s) => `(${sqlLiteral(s.code)}, ${sqlLiteral(s.countryCode)}, ${sqlLiteral(s.name)})`)
    .join(',\n    ');
  pgm.sql(`
    INSERT INTO country_subdivision (code, country_code, name) VALUES
    ${subdivisions}
    ON CONFLICT (code) DO NOTHING;
  `);
}

// Intentionally a no-op. These rows are FK targets for product, product_concept,
// invoice_line, merchant.default_category_id, country_subdivision, and user regions, so a
// DELETE would throw on any populated stage and strand rollbacks of later migrations
// mid-way. Seeded reference data is harmless to retain; the tables themselves are dropped
// (CASCADE) by the migrations that created them when the schema is fully torn down, and
// up() is idempotent so re-applying is safe.
export async function down(): Promise<void> {}
