// ISO 3166 reference data for the launch + roadmap markets. `country` is ISO
// 3166-1 alpha-2; `subdivision.code` is ISO 3166-2. These are the single source
// of truth for the onboarding country/region dropdowns and region-code
// validation. Top-level subdivisions only. The four UK nations (England,
// Scotland, Wales, Northern Ireland) are modelled as separate top-level
// countries with project-local codes EN/SC/WA/NI (no ISO 3166-1 alpha-2 exists),
// each carrying its own regions, rather than as subdivisions of GB.

export interface CountrySeed {
  code: string;
  name: string;
}

export interface SubdivisionSeed {
  code: string;
  country_code: string;
  name: string;
}

export const countrySeed: CountrySeed[] = [
  // UK nations as separate top-level countries. No ISO 3166-1 alpha-2 exists for
  // them, so EN/SC/WA/NI are project-local codes fitting the CHAR(2) country.code.
  { code: 'EN', name: 'England' },
  { code: 'SC', name: 'Scotland' },
  { code: 'WA', name: 'Wales' },
  { code: 'NI', name: 'Northern Ireland' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'US', name: 'United States' },
  { code: 'IT', name: 'Italy' },
  { code: 'PT', name: 'Portugal' },
  { code: 'ES', name: 'Spain' },
  { code: 'CA', name: 'Canada' },
  { code: 'BR', name: 'Brazil' },
  { code: 'CN', name: 'China' },
  { code: 'AT', name: 'Austria' },
  { code: 'DK', name: 'Denmark' },
];

export const subdivisionSeed: SubdivisionSeed[] = [
  // ── England (9 statistical regions) ─────────────────────────────────────────
  { code: 'EN-NE', country_code: 'EN', name: 'North East' },
  { code: 'EN-NW', country_code: 'EN', name: 'North West' },
  { code: 'EN-YH', country_code: 'EN', name: 'Yorkshire and the Humber' },
  { code: 'EN-EM', country_code: 'EN', name: 'East Midlands' },
  { code: 'EN-WM', country_code: 'EN', name: 'West Midlands' },
  { code: 'EN-EE', country_code: 'EN', name: 'East of England' },
  { code: 'EN-LDN', country_code: 'EN', name: 'London' },
  { code: 'EN-SE', country_code: 'EN', name: 'South East' },
  { code: 'EN-SW', country_code: 'EN', name: 'South West' },

  // ── Scotland (32 council areas) ─────────────────────────────────────────────
  { code: 'SC-ABE', country_code: 'SC', name: 'Aberdeen City' },
  { code: 'SC-ABD', country_code: 'SC', name: 'Aberdeenshire' },
  { code: 'SC-ANS', country_code: 'SC', name: 'Angus' },
  { code: 'SC-AGB', country_code: 'SC', name: 'Argyll and Bute' },
  { code: 'SC-CLK', country_code: 'SC', name: 'Clackmannanshire' },
  { code: 'SC-DGY', country_code: 'SC', name: 'Dumfries and Galloway' },
  { code: 'SC-DND', country_code: 'SC', name: 'Dundee City' },
  { code: 'SC-EAY', country_code: 'SC', name: 'East Ayrshire' },
  { code: 'SC-EDU', country_code: 'SC', name: 'East Dunbartonshire' },
  { code: 'SC-ELN', country_code: 'SC', name: 'East Lothian' },
  { code: 'SC-ERW', country_code: 'SC', name: 'East Renfrewshire' },
  { code: 'SC-EDH', country_code: 'SC', name: 'City of Edinburgh' },
  { code: 'SC-ELS', country_code: 'SC', name: 'Na h-Eileanan Siar' },
  { code: 'SC-FAL', country_code: 'SC', name: 'Falkirk' },
  { code: 'SC-FIF', country_code: 'SC', name: 'Fife' },
  { code: 'SC-GLG', country_code: 'SC', name: 'Glasgow City' },
  { code: 'SC-HLD', country_code: 'SC', name: 'Highland' },
  { code: 'SC-IVC', country_code: 'SC', name: 'Inverclyde' },
  { code: 'SC-MLN', country_code: 'SC', name: 'Midlothian' },
  { code: 'SC-MRY', country_code: 'SC', name: 'Moray' },
  { code: 'SC-NAY', country_code: 'SC', name: 'North Ayrshire' },
  { code: 'SC-NLK', country_code: 'SC', name: 'North Lanarkshire' },
  { code: 'SC-ORK', country_code: 'SC', name: 'Orkney Islands' },
  { code: 'SC-PKN', country_code: 'SC', name: 'Perth and Kinross' },
  { code: 'SC-RFW', country_code: 'SC', name: 'Renfrewshire' },
  { code: 'SC-SCB', country_code: 'SC', name: 'Scottish Borders' },
  { code: 'SC-ZET', country_code: 'SC', name: 'Shetland Islands' },
  { code: 'SC-SAY', country_code: 'SC', name: 'South Ayrshire' },
  { code: 'SC-SLK', country_code: 'SC', name: 'South Lanarkshire' },
  { code: 'SC-STG', country_code: 'SC', name: 'Stirling' },
  { code: 'SC-WDU', country_code: 'SC', name: 'West Dunbartonshire' },
  { code: 'SC-WLN', country_code: 'SC', name: 'West Lothian' },

  // ── Wales (22 principal areas) ──────────────────────────────────────────────
  { code: 'WA-BGW', country_code: 'WA', name: 'Blaenau Gwent' },
  { code: 'WA-BGE', country_code: 'WA', name: 'Bridgend' },
  { code: 'WA-CAY', country_code: 'WA', name: 'Caerphilly' },
  { code: 'WA-CRF', country_code: 'WA', name: 'Cardiff' },
  { code: 'WA-CMN', country_code: 'WA', name: 'Carmarthenshire' },
  { code: 'WA-CGN', country_code: 'WA', name: 'Ceredigion' },
  { code: 'WA-CWY', country_code: 'WA', name: 'Conwy' },
  { code: 'WA-DEN', country_code: 'WA', name: 'Denbighshire' },
  { code: 'WA-FLN', country_code: 'WA', name: 'Flintshire' },
  { code: 'WA-GWN', country_code: 'WA', name: 'Gwynedd' },
  { code: 'WA-AGY', country_code: 'WA', name: 'Isle of Anglesey' },
  { code: 'WA-MTY', country_code: 'WA', name: 'Merthyr Tydfil' },
  { code: 'WA-MON', country_code: 'WA', name: 'Monmouthshire' },
  { code: 'WA-NTL', country_code: 'WA', name: 'Neath Port Talbot' },
  { code: 'WA-NWP', country_code: 'WA', name: 'Newport' },
  { code: 'WA-PEM', country_code: 'WA', name: 'Pembrokeshire' },
  { code: 'WA-POW', country_code: 'WA', name: 'Powys' },
  { code: 'WA-RCT', country_code: 'WA', name: 'Rhondda Cynon Taf' },
  { code: 'WA-SWA', country_code: 'WA', name: 'Swansea' },
  { code: 'WA-TOF', country_code: 'WA', name: 'Torfaen' },
  { code: 'WA-VGL', country_code: 'WA', name: 'Vale of Glamorgan' },
  { code: 'WA-WRX', country_code: 'WA', name: 'Wrexham' },

  // ── Northern Ireland (11 districts) ─────────────────────────────────────────
  { code: 'NI-ANN', country_code: 'NI', name: 'Antrim and Newtownabbey' },
  { code: 'NI-AND', country_code: 'NI', name: 'Ards and North Down' },
  { code: 'NI-ABC', country_code: 'NI', name: 'Armagh City, Banbridge and Craigavon' },
  { code: 'NI-BFS', country_code: 'NI', name: 'Belfast' },
  { code: 'NI-CCG', country_code: 'NI', name: 'Causeway Coast and Glens' },
  { code: 'NI-DRS', country_code: 'NI', name: 'Derry City and Strabane' },
  { code: 'NI-FMO', country_code: 'NI', name: 'Fermanagh and Omagh' },
  { code: 'NI-LBC', country_code: 'NI', name: 'Lisburn and Castlereagh' },
  { code: 'NI-MEA', country_code: 'NI', name: 'Mid and East Antrim' },
  { code: 'NI-MUL', country_code: 'NI', name: 'Mid Ulster' },
  { code: 'NI-NMD', country_code: 'NI', name: 'Newry, Mourne and Down' },

  // ── Netherlands (12 provinces) ──────────────────────────────────────────────
  { code: 'NL-DR', country_code: 'NL', name: 'Drenthe' },
  { code: 'NL-FL', country_code: 'NL', name: 'Flevoland' },
  { code: 'NL-FR', country_code: 'NL', name: 'Friesland' },
  { code: 'NL-GE', country_code: 'NL', name: 'Gelderland' },
  { code: 'NL-GR', country_code: 'NL', name: 'Groningen' },
  { code: 'NL-LI', country_code: 'NL', name: 'Limburg' },
  { code: 'NL-NB', country_code: 'NL', name: 'Noord-Brabant' },
  { code: 'NL-NH', country_code: 'NL', name: 'Noord-Holland' },
  { code: 'NL-OV', country_code: 'NL', name: 'Overijssel' },
  { code: 'NL-UT', country_code: 'NL', name: 'Utrecht' },
  { code: 'NL-ZE', country_code: 'NL', name: 'Zeeland' },
  { code: 'NL-ZH', country_code: 'NL', name: 'Zuid-Holland' },

  // ── France (18 regions) ─────────────────────────────────────────────────────
  { code: 'FR-ARA', country_code: 'FR', name: 'Auvergne-Rhône-Alpes' },
  { code: 'FR-BFC', country_code: 'FR', name: 'Bourgogne-Franche-Comté' },
  { code: 'FR-BRE', country_code: 'FR', name: 'Bretagne' },
  { code: 'FR-CVL', country_code: 'FR', name: 'Centre-Val de Loire' },
  { code: 'FR-COR', country_code: 'FR', name: 'Corse' },
  { code: 'FR-GES', country_code: 'FR', name: 'Grand Est' },
  { code: 'FR-HDF', country_code: 'FR', name: 'Hauts-de-France' },
  { code: 'FR-IDF', country_code: 'FR', name: 'Île-de-France' },
  { code: 'FR-NOR', country_code: 'FR', name: 'Normandie' },
  { code: 'FR-NAQ', country_code: 'FR', name: 'Nouvelle-Aquitaine' },
  { code: 'FR-OCC', country_code: 'FR', name: 'Occitanie' },
  { code: 'FR-PDL', country_code: 'FR', name: 'Pays de la Loire' },
  { code: 'FR-PAC', country_code: 'FR', name: "Provence-Alpes-Côte d'Azur" },
  { code: 'FR-GP', country_code: 'FR', name: 'Guadeloupe' },
  { code: 'FR-MQ', country_code: 'FR', name: 'Martinique' },
  { code: 'FR-GF', country_code: 'FR', name: 'Guyane' },
  { code: 'FR-RE', country_code: 'FR', name: 'La Réunion' },
  { code: 'FR-YT', country_code: 'FR', name: 'Mayotte' },

  // ── Germany (16 Länder) ─────────────────────────────────────────────────────
  { code: 'DE-BW', country_code: 'DE', name: 'Baden-Württemberg' },
  { code: 'DE-BY', country_code: 'DE', name: 'Bayern' },
  { code: 'DE-BE', country_code: 'DE', name: 'Berlin' },
  { code: 'DE-BB', country_code: 'DE', name: 'Brandenburg' },
  { code: 'DE-HB', country_code: 'DE', name: 'Bremen' },
  { code: 'DE-HH', country_code: 'DE', name: 'Hamburg' },
  { code: 'DE-HE', country_code: 'DE', name: 'Hessen' },
  { code: 'DE-MV', country_code: 'DE', name: 'Mecklenburg-Vorpommern' },
  { code: 'DE-NI', country_code: 'DE', name: 'Niedersachsen' },
  { code: 'DE-NW', country_code: 'DE', name: 'Nordrhein-Westfalen' },
  { code: 'DE-RP', country_code: 'DE', name: 'Rheinland-Pfalz' },
  { code: 'DE-SL', country_code: 'DE', name: 'Saarland' },
  { code: 'DE-SN', country_code: 'DE', name: 'Sachsen' },
  { code: 'DE-ST', country_code: 'DE', name: 'Sachsen-Anhalt' },
  { code: 'DE-SH', country_code: 'DE', name: 'Schleswig-Holstein' },
  { code: 'DE-TH', country_code: 'DE', name: 'Thüringen' },

  // ── United States (50 states + DC) ──────────────────────────────────────────
  { code: 'US-AL', country_code: 'US', name: 'Alabama' },
  { code: 'US-AK', country_code: 'US', name: 'Alaska' },
  { code: 'US-AZ', country_code: 'US', name: 'Arizona' },
  { code: 'US-AR', country_code: 'US', name: 'Arkansas' },
  { code: 'US-CA', country_code: 'US', name: 'California' },
  { code: 'US-CO', country_code: 'US', name: 'Colorado' },
  { code: 'US-CT', country_code: 'US', name: 'Connecticut' },
  { code: 'US-DE', country_code: 'US', name: 'Delaware' },
  { code: 'US-FL', country_code: 'US', name: 'Florida' },
  { code: 'US-GA', country_code: 'US', name: 'Georgia' },
  { code: 'US-HI', country_code: 'US', name: 'Hawaii' },
  { code: 'US-ID', country_code: 'US', name: 'Idaho' },
  { code: 'US-IL', country_code: 'US', name: 'Illinois' },
  { code: 'US-IN', country_code: 'US', name: 'Indiana' },
  { code: 'US-IA', country_code: 'US', name: 'Iowa' },
  { code: 'US-KS', country_code: 'US', name: 'Kansas' },
  { code: 'US-KY', country_code: 'US', name: 'Kentucky' },
  { code: 'US-LA', country_code: 'US', name: 'Louisiana' },
  { code: 'US-ME', country_code: 'US', name: 'Maine' },
  { code: 'US-MD', country_code: 'US', name: 'Maryland' },
  { code: 'US-MA', country_code: 'US', name: 'Massachusetts' },
  { code: 'US-MI', country_code: 'US', name: 'Michigan' },
  { code: 'US-MN', country_code: 'US', name: 'Minnesota' },
  { code: 'US-MS', country_code: 'US', name: 'Mississippi' },
  { code: 'US-MO', country_code: 'US', name: 'Missouri' },
  { code: 'US-MT', country_code: 'US', name: 'Montana' },
  { code: 'US-NE', country_code: 'US', name: 'Nebraska' },
  { code: 'US-NV', country_code: 'US', name: 'Nevada' },
  { code: 'US-NH', country_code: 'US', name: 'New Hampshire' },
  { code: 'US-NJ', country_code: 'US', name: 'New Jersey' },
  { code: 'US-NM', country_code: 'US', name: 'New Mexico' },
  { code: 'US-NY', country_code: 'US', name: 'New York' },
  { code: 'US-NC', country_code: 'US', name: 'North Carolina' },
  { code: 'US-ND', country_code: 'US', name: 'North Dakota' },
  { code: 'US-OH', country_code: 'US', name: 'Ohio' },
  { code: 'US-OK', country_code: 'US', name: 'Oklahoma' },
  { code: 'US-OR', country_code: 'US', name: 'Oregon' },
  { code: 'US-PA', country_code: 'US', name: 'Pennsylvania' },
  { code: 'US-RI', country_code: 'US', name: 'Rhode Island' },
  { code: 'US-SC', country_code: 'US', name: 'South Carolina' },
  { code: 'US-SD', country_code: 'US', name: 'South Dakota' },
  { code: 'US-TN', country_code: 'US', name: 'Tennessee' },
  { code: 'US-TX', country_code: 'US', name: 'Texas' },
  { code: 'US-UT', country_code: 'US', name: 'Utah' },
  { code: 'US-VT', country_code: 'US', name: 'Vermont' },
  { code: 'US-VA', country_code: 'US', name: 'Virginia' },
  { code: 'US-WA', country_code: 'US', name: 'Washington' },
  { code: 'US-WV', country_code: 'US', name: 'West Virginia' },
  { code: 'US-WI', country_code: 'US', name: 'Wisconsin' },
  { code: 'US-WY', country_code: 'US', name: 'Wyoming' },
  { code: 'US-DC', country_code: 'US', name: 'District of Columbia' },

  // ── Italy (20 regions) ──────────────────────────────────────────────────────
  { code: 'IT-65', country_code: 'IT', name: 'Abruzzo' },
  { code: 'IT-77', country_code: 'IT', name: 'Basilicata' },
  { code: 'IT-78', country_code: 'IT', name: 'Calabria' },
  { code: 'IT-72', country_code: 'IT', name: 'Campania' },
  { code: 'IT-45', country_code: 'IT', name: 'Emilia-Romagna' },
  { code: 'IT-36', country_code: 'IT', name: 'Friuli Venezia Giulia' },
  { code: 'IT-62', country_code: 'IT', name: 'Lazio' },
  { code: 'IT-42', country_code: 'IT', name: 'Liguria' },
  { code: 'IT-25', country_code: 'IT', name: 'Lombardia' },
  { code: 'IT-57', country_code: 'IT', name: 'Marche' },
  { code: 'IT-67', country_code: 'IT', name: 'Molise' },
  { code: 'IT-21', country_code: 'IT', name: 'Piemonte' },
  { code: 'IT-75', country_code: 'IT', name: 'Puglia' },
  { code: 'IT-88', country_code: 'IT', name: 'Sardegna' },
  { code: 'IT-82', country_code: 'IT', name: 'Sicilia' },
  { code: 'IT-52', country_code: 'IT', name: 'Toscana' },
  { code: 'IT-32', country_code: 'IT', name: 'Trentino-Alto Adige' },
  { code: 'IT-55', country_code: 'IT', name: 'Umbria' },
  { code: 'IT-23', country_code: 'IT', name: "Valle d'Aosta" },
  { code: 'IT-34', country_code: 'IT', name: 'Veneto' },

  // ── Portugal (18 districts + 2 autonomous regions) ──────────────────────────
  { code: 'PT-01', country_code: 'PT', name: 'Aveiro' },
  { code: 'PT-02', country_code: 'PT', name: 'Beja' },
  { code: 'PT-03', country_code: 'PT', name: 'Braga' },
  { code: 'PT-04', country_code: 'PT', name: 'Bragança' },
  { code: 'PT-05', country_code: 'PT', name: 'Castelo Branco' },
  { code: 'PT-06', country_code: 'PT', name: 'Coimbra' },
  { code: 'PT-07', country_code: 'PT', name: 'Évora' },
  { code: 'PT-08', country_code: 'PT', name: 'Faro' },
  { code: 'PT-09', country_code: 'PT', name: 'Guarda' },
  { code: 'PT-10', country_code: 'PT', name: 'Leiria' },
  { code: 'PT-11', country_code: 'PT', name: 'Lisboa' },
  { code: 'PT-12', country_code: 'PT', name: 'Portalegre' },
  { code: 'PT-13', country_code: 'PT', name: 'Porto' },
  { code: 'PT-14', country_code: 'PT', name: 'Santarém' },
  { code: 'PT-15', country_code: 'PT', name: 'Setúbal' },
  { code: 'PT-16', country_code: 'PT', name: 'Viana do Castelo' },
  { code: 'PT-17', country_code: 'PT', name: 'Vila Real' },
  { code: 'PT-18', country_code: 'PT', name: 'Viseu' },
  { code: 'PT-20', country_code: 'PT', name: 'Região Autónoma dos Açores' },
  { code: 'PT-30', country_code: 'PT', name: 'Região Autónoma da Madeira' },

  // ── Spain (17 communities + 2 autonomous cities) ────────────────────────────
  { code: 'ES-AN', country_code: 'ES', name: 'Andalucía' },
  { code: 'ES-AR', country_code: 'ES', name: 'Aragón' },
  { code: 'ES-AS', country_code: 'ES', name: 'Asturias' },
  { code: 'ES-CB', country_code: 'ES', name: 'Cantabria' },
  { code: 'ES-CL', country_code: 'ES', name: 'Castilla y León' },
  { code: 'ES-CM', country_code: 'ES', name: 'Castilla-La Mancha' },
  { code: 'ES-CT', country_code: 'ES', name: 'Cataluña' },
  { code: 'ES-EX', country_code: 'ES', name: 'Extremadura' },
  { code: 'ES-GA', country_code: 'ES', name: 'Galicia' },
  { code: 'ES-IB', country_code: 'ES', name: 'Illes Balears' },
  { code: 'ES-CN', country_code: 'ES', name: 'Canarias' },
  { code: 'ES-RI', country_code: 'ES', name: 'La Rioja' },
  { code: 'ES-MD', country_code: 'ES', name: 'Madrid' },
  { code: 'ES-MC', country_code: 'ES', name: 'Murcia' },
  { code: 'ES-NC', country_code: 'ES', name: 'Navarra' },
  { code: 'ES-PV', country_code: 'ES', name: 'País Vasco' },
  { code: 'ES-VC', country_code: 'ES', name: 'Comunidad Valenciana' },
  { code: 'ES-CE', country_code: 'ES', name: 'Ceuta' },
  { code: 'ES-ML', country_code: 'ES', name: 'Melilla' },

  // ── Canada (10 provinces + 3 territories) ───────────────────────────────────
  { code: 'CA-AB', country_code: 'CA', name: 'Alberta' },
  { code: 'CA-BC', country_code: 'CA', name: 'British Columbia' },
  { code: 'CA-MB', country_code: 'CA', name: 'Manitoba' },
  { code: 'CA-NB', country_code: 'CA', name: 'New Brunswick' },
  { code: 'CA-NL', country_code: 'CA', name: 'Newfoundland and Labrador' },
  { code: 'CA-NS', country_code: 'CA', name: 'Nova Scotia' },
  { code: 'CA-ON', country_code: 'CA', name: 'Ontario' },
  { code: 'CA-PE', country_code: 'CA', name: 'Prince Edward Island' },
  { code: 'CA-QC', country_code: 'CA', name: 'Quebec' },
  { code: 'CA-SK', country_code: 'CA', name: 'Saskatchewan' },
  { code: 'CA-NT', country_code: 'CA', name: 'Northwest Territories' },
  { code: 'CA-NU', country_code: 'CA', name: 'Nunavut' },
  { code: 'CA-YT', country_code: 'CA', name: 'Yukon' },

  // ── Brazil (26 states + Federal District) ───────────────────────────────────
  { code: 'BR-AC', country_code: 'BR', name: 'Acre' },
  { code: 'BR-AL', country_code: 'BR', name: 'Alagoas' },
  { code: 'BR-AP', country_code: 'BR', name: 'Amapá' },
  { code: 'BR-AM', country_code: 'BR', name: 'Amazonas' },
  { code: 'BR-BA', country_code: 'BR', name: 'Bahia' },
  { code: 'BR-CE', country_code: 'BR', name: 'Ceará' },
  { code: 'BR-DF', country_code: 'BR', name: 'Distrito Federal' },
  { code: 'BR-ES', country_code: 'BR', name: 'Espírito Santo' },
  { code: 'BR-GO', country_code: 'BR', name: 'Goiás' },
  { code: 'BR-MA', country_code: 'BR', name: 'Maranhão' },
  { code: 'BR-MT', country_code: 'BR', name: 'Mato Grosso' },
  { code: 'BR-MS', country_code: 'BR', name: 'Mato Grosso do Sul' },
  { code: 'BR-MG', country_code: 'BR', name: 'Minas Gerais' },
  { code: 'BR-PA', country_code: 'BR', name: 'Pará' },
  { code: 'BR-PB', country_code: 'BR', name: 'Paraíba' },
  { code: 'BR-PR', country_code: 'BR', name: 'Paraná' },
  { code: 'BR-PE', country_code: 'BR', name: 'Pernambuco' },
  { code: 'BR-PI', country_code: 'BR', name: 'Piauí' },
  { code: 'BR-RJ', country_code: 'BR', name: 'Rio de Janeiro' },
  { code: 'BR-RN', country_code: 'BR', name: 'Rio Grande do Norte' },
  { code: 'BR-RS', country_code: 'BR', name: 'Rio Grande do Sul' },
  { code: 'BR-RO', country_code: 'BR', name: 'Rondônia' },
  { code: 'BR-RR', country_code: 'BR', name: 'Roraima' },
  { code: 'BR-SC', country_code: 'BR', name: 'Santa Catarina' },
  { code: 'BR-SP', country_code: 'BR', name: 'São Paulo' },
  { code: 'BR-SE', country_code: 'BR', name: 'Sergipe' },
  { code: 'BR-TO', country_code: 'BR', name: 'Tocantins' },

  // ── China (provinces, regions, municipalities, SARs) ────────────────────────
  { code: 'CN-BJ', country_code: 'CN', name: 'Beijing' },
  { code: 'CN-TJ', country_code: 'CN', name: 'Tianjin' },
  { code: 'CN-HE', country_code: 'CN', name: 'Hebei' },
  { code: 'CN-SX', country_code: 'CN', name: 'Shanxi' },
  { code: 'CN-NM', country_code: 'CN', name: 'Inner Mongolia' },
  { code: 'CN-LN', country_code: 'CN', name: 'Liaoning' },
  { code: 'CN-JL', country_code: 'CN', name: 'Jilin' },
  { code: 'CN-HL', country_code: 'CN', name: 'Heilongjiang' },
  { code: 'CN-SH', country_code: 'CN', name: 'Shanghai' },
  { code: 'CN-JS', country_code: 'CN', name: 'Jiangsu' },
  { code: 'CN-ZJ', country_code: 'CN', name: 'Zhejiang' },
  { code: 'CN-AH', country_code: 'CN', name: 'Anhui' },
  { code: 'CN-FJ', country_code: 'CN', name: 'Fujian' },
  { code: 'CN-JX', country_code: 'CN', name: 'Jiangxi' },
  { code: 'CN-SD', country_code: 'CN', name: 'Shandong' },
  { code: 'CN-HA', country_code: 'CN', name: 'Henan' },
  { code: 'CN-HB', country_code: 'CN', name: 'Hubei' },
  { code: 'CN-HN', country_code: 'CN', name: 'Hunan' },
  { code: 'CN-GD', country_code: 'CN', name: 'Guangdong' },
  { code: 'CN-GX', country_code: 'CN', name: 'Guangxi' },
  { code: 'CN-HI', country_code: 'CN', name: 'Hainan' },
  { code: 'CN-CQ', country_code: 'CN', name: 'Chongqing' },
  { code: 'CN-SC', country_code: 'CN', name: 'Sichuan' },
  { code: 'CN-GZ', country_code: 'CN', name: 'Guizhou' },
  { code: 'CN-YN', country_code: 'CN', name: 'Yunnan' },
  { code: 'CN-XZ', country_code: 'CN', name: 'Tibet' },
  { code: 'CN-SN', country_code: 'CN', name: 'Shaanxi' },
  { code: 'CN-GS', country_code: 'CN', name: 'Gansu' },
  { code: 'CN-QH', country_code: 'CN', name: 'Qinghai' },
  { code: 'CN-NX', country_code: 'CN', name: 'Ningxia' },
  { code: 'CN-XJ', country_code: 'CN', name: 'Xinjiang' },
  { code: 'CN-TW', country_code: 'CN', name: 'Taiwan' },
  { code: 'CN-HK', country_code: 'CN', name: 'Hong Kong' },
  { code: 'CN-MO', country_code: 'CN', name: 'Macao' },

  // ── Austria (9 states) ──────────────────────────────────────────────────────
  { code: 'AT-1', country_code: 'AT', name: 'Burgenland' },
  { code: 'AT-2', country_code: 'AT', name: 'Kärnten' },
  { code: 'AT-3', country_code: 'AT', name: 'Niederösterreich' },
  { code: 'AT-4', country_code: 'AT', name: 'Oberösterreich' },
  { code: 'AT-5', country_code: 'AT', name: 'Salzburg' },
  { code: 'AT-6', country_code: 'AT', name: 'Steiermark' },
  { code: 'AT-7', country_code: 'AT', name: 'Tirol' },
  { code: 'AT-8', country_code: 'AT', name: 'Vorarlberg' },
  { code: 'AT-9', country_code: 'AT', name: 'Wien' },

  // ── Denmark (5 regions) ─────────────────────────────────────────────────────
  { code: 'DK-84', country_code: 'DK', name: 'Hovedstaden' },
  { code: 'DK-82', country_code: 'DK', name: 'Midtjylland' },
  { code: 'DK-81', country_code: 'DK', name: 'Nordjylland' },
  { code: 'DK-85', country_code: 'DK', name: 'Sjælland' },
  { code: 'DK-83', country_code: 'DK', name: 'Syddanmark' },
];
