export interface Tag {
  tag_key: string;
  display_name_nl: string;
  display_name_en: string;
  trigger_map: Array<{ category_id?: string; merchant_brand?: string; min_spend_share?: number }>;
}

const tagVocabulary: Tag[] = [
  { tag_key: 'weekly-groceries', display_name_nl: 'Weekboodschappen', display_name_en: 'Weekly groceries', trigger_map: [{ category_id: 'cat-groceries', min_spend_share: 0.3 }] },
  { tag_key: 'organic', display_name_nl: 'Biologisch', display_name_en: 'Organic', trigger_map: [{ category_id: 'cat-dairy' }, { category_id: 'cat-produce' }] },
  { tag_key: 'frozen-foods', display_name_nl: 'Diepvriesproducten', display_name_en: 'Frozen foods', trigger_map: [{ category_id: 'cat-frozen' }] },
  { tag_key: 'snacks', display_name_nl: 'Snacks', display_name_en: 'Snacks', trigger_map: [{ category_id: 'cat-snacks' }] },
  { tag_key: 'beverages', display_name_nl: 'Dranken', display_name_en: 'Beverages', trigger_map: [{ category_id: 'cat-beverages' }] },
  { tag_key: 'alcohol', display_name_nl: 'Alcohol', display_name_en: 'Alcohol', trigger_map: [{ category_id: 'cat-alcohol' }] },
  { tag_key: 'bakery', display_name_nl: 'Bakkerij', display_name_en: 'Bakery', trigger_map: [{ category_id: 'cat-bakery' }] },
  { tag_key: 'dairy', display_name_nl: 'Zuivel', display_name_en: 'Dairy', trigger_map: [{ category_id: 'cat-dairy' }] },
  { tag_key: 'produce', display_name_nl: 'Groente & Fruit', display_name_en: 'Produce', trigger_map: [{ category_id: 'cat-produce' }] },
  { tag_key: 'meat-fish', display_name_nl: 'Vlees & Vis', display_name_en: 'Meat & Fish', trigger_map: [{ category_id: 'cat-meat-fish' }] },
  { tag_key: 'pantry', display_name_nl: 'Voorraadkast', display_name_en: 'Pantry staples', trigger_map: [{ category_id: 'cat-pantry' }] },
  { tag_key: 'household-supplies', display_name_nl: 'Huishoudartikelen', display_name_en: 'Household supplies', trigger_map: [{ category_id: 'cat-household' }] },
  { tag_key: 'cleaning', display_name_nl: 'Schoonmaak', display_name_en: 'Cleaning', trigger_map: [{ category_id: 'cat-household', min_spend_share: 0.2 }] },
  { tag_key: 'personal-care', display_name_nl: 'Persoonlijke verzorging', display_name_en: 'Personal care', trigger_map: [{ category_id: 'cat-personal-care' }] },
  { tag_key: 'pharmacy', display_name_nl: 'Apotheek', display_name_en: 'Pharmacy', trigger_map: [{ category_id: 'cat-pharmacy' }] },
  { tag_key: 'baby-care', display_name_nl: 'Babyverzorging', display_name_en: 'Baby care', trigger_map: [{ category_id: 'cat-baby' }] },
  { tag_key: 'pet-food', display_name_nl: 'Dierenvoeding', display_name_en: 'Pet food', trigger_map: [{ category_id: 'cat-pet' }] },
  { tag_key: 'dining-out', display_name_nl: 'Uit eten', display_name_en: 'Dining out', trigger_map: [{ category_id: 'cat-dining-out' }] },
  { tag_key: 'takeaway', display_name_nl: 'Afhalen', display_name_en: 'Takeaway', trigger_map: [{ category_id: 'cat-dining-out', min_spend_share: 0.5 }] },
  { tag_key: 'fuel', display_name_nl: 'Brandstof', display_name_en: 'Fuel', trigger_map: [{ category_id: 'cat-transport' }] },
  { tag_key: 'transport', display_name_nl: 'Transport', display_name_en: 'Transport', trigger_map: [{ category_id: 'cat-transport' }] },
  { tag_key: 'clothing', display_name_nl: 'Kleding', display_name_en: 'Clothing', trigger_map: [{ category_id: 'cat-clothing' }] },
  { tag_key: 'electronics', display_name_nl: 'Elektronica', display_name_en: 'Electronics', trigger_map: [{ category_id: 'cat-electronics' }] },
  { tag_key: 'health', display_name_nl: 'Gezondheid', display_name_en: 'Health', trigger_map: [{ category_id: 'cat-health' }] },
  { tag_key: 'home-garden', display_name_nl: 'Huis & Tuin', display_name_en: 'Home & Garden', trigger_map: [{ category_id: 'cat-home-garden' }] },
  { tag_key: 'entertainment', display_name_nl: 'Entertainment', display_name_en: 'Entertainment', trigger_map: [{ category_id: 'cat-entertainment' }] },
  { tag_key: 'services', display_name_nl: 'Diensten', display_name_en: 'Services', trigger_map: [{ category_id: 'cat-services' }] },
  { tag_key: 'subscription', display_name_nl: 'Abonnement', display_name_en: 'Subscription', trigger_map: [{ category_id: 'cat-services' }] },
  { tag_key: 'discount-find', display_name_nl: 'Koopje gevonden', display_name_en: 'Discount find', trigger_map: [] },
  { tag_key: 'bulk-buy', display_name_nl: 'Grootverpakking', display_name_en: 'Bulk buy', trigger_map: [] },
  { tag_key: 'bbq', display_name_nl: 'BBQ', display_name_en: 'BBQ', trigger_map: [{ category_id: 'cat-meat-fish' }, { category_id: 'cat-beverages' }] },
  { tag_key: 'picnic', display_name_nl: 'Picknick', display_name_en: 'Picnic', trigger_map: [{ category_id: 'cat-snacks' }, { category_id: 'cat-beverages' }] },
  { tag_key: 'birthday', display_name_nl: 'Verjaardag', display_name_en: 'Birthday', trigger_map: [] },
  { tag_key: 'holiday', display_name_nl: 'Vakantie', display_name_en: 'Holiday', trigger_map: [] },
  { tag_key: 'christmas', display_name_nl: 'Kerst', display_name_en: 'Christmas', trigger_map: [] },
  { tag_key: 'back-to-school', display_name_nl: 'Terug naar school', display_name_en: 'Back to school', trigger_map: [{ category_id: 'cat-electronics' }, { category_id: 'cat-clothing' }] },
  { tag_key: 'road-trip', display_name_nl: 'Road trip', display_name_en: 'Road trip', trigger_map: [{ category_id: 'cat-transport' }, { category_id: 'cat-snacks' }] },
  { tag_key: 'home-office', display_name_nl: 'Thuiswerken', display_name_en: 'Home office', trigger_map: [{ category_id: 'cat-electronics' }, { category_id: 'cat-services' }] },
  { tag_key: 'gym', display_name_nl: 'Sportschool', display_name_en: 'Gym', trigger_map: [{ category_id: 'cat-health' }, { category_id: 'cat-services' }] },
  { tag_key: 'sports', display_name_nl: 'Sport', display_name_en: 'Sports', trigger_map: [{ category_id: 'cat-health' }] },
  { tag_key: 'books', display_name_nl: 'Boeken', display_name_en: 'Books', trigger_map: [{ category_id: 'cat-entertainment' }] },
  { tag_key: 'kids', display_name_nl: 'Kinderen', display_name_en: 'Kids', trigger_map: [{ category_id: 'cat-baby' }] },
  { tag_key: 'beauty', display_name_nl: 'Schoonheid', display_name_en: 'Beauty', trigger_map: [{ category_id: 'cat-personal-care' }] },
  { tag_key: 'hair-care', display_name_nl: 'Haarverzorging', display_name_en: 'Hair care', trigger_map: [{ category_id: 'cat-personal-care', min_spend_share: 0.2 }] },
  { tag_key: 'skin-care', display_name_nl: 'Huidverzorging', display_name_en: 'Skin care', trigger_map: [{ category_id: 'cat-personal-care', min_spend_share: 0.2 }] },
  { tag_key: 'vitamins', display_name_nl: 'Vitamines', display_name_en: 'Vitamins', trigger_map: [{ category_id: 'cat-health' }, { category_id: 'cat-pharmacy' }] },
  { tag_key: 'medication', display_name_nl: 'Medicatie', display_name_en: 'Medication', trigger_map: [{ category_id: 'cat-pharmacy' }] },
  { tag_key: 'gifts', display_name_nl: 'Cadeaus', display_name_en: 'Gifts', trigger_map: [] },
  { tag_key: 'travel', display_name_nl: 'Reizen', display_name_en: 'Travel', trigger_map: [{ category_id: 'cat-transport' }] },
  { tag_key: 'insurance', display_name_nl: 'Verzekering', display_name_en: 'Insurance', trigger_map: [{ category_id: 'cat-services' }] },
  { tag_key: 'utilities', display_name_nl: 'Nutsvoorzieningen', display_name_en: 'Utilities', trigger_map: [{ category_id: 'cat-services' }] },
  { tag_key: 'rent', display_name_nl: 'Huur', display_name_en: 'Rent', trigger_map: [{ category_id: 'cat-services' }] },
  { tag_key: 'eating-healthy', display_name_nl: 'Gezond eten', display_name_en: 'Eating healthy', trigger_map: [{ category_id: 'cat-produce' }, { category_id: 'cat-dairy' }] },
  { tag_key: 'vegetarian', display_name_nl: 'Vegetarisch', display_name_en: 'Vegetarian', trigger_map: [{ category_id: 'cat-produce' }, { category_id: 'cat-dairy' }] },
  { tag_key: 'vegan', display_name_nl: 'Veganistisch', display_name_en: 'Vegan', trigger_map: [{ category_id: 'cat-produce' }] },
  { tag_key: 'gluten-free', display_name_nl: 'Glutenvrij', display_name_en: 'Gluten-free', trigger_map: [{ category_id: 'cat-bakery' }, { category_id: 'cat-pantry' }] },
  { tag_key: 'meal-prep', display_name_nl: 'Maaltijdprep', display_name_en: 'Meal prep', trigger_map: [{ category_id: 'cat-groceries', min_spend_share: 0.4 }] },
  { tag_key: 'coffee-shop', display_name_nl: 'Koffieshop', display_name_en: 'Coffee shop', trigger_map: [{ category_id: 'cat-dining-out' }] },
  { tag_key: 'fast-food', display_name_nl: 'Fast food', display_name_en: 'Fast food', trigger_map: [{ category_id: 'cat-dining-out' }] },
  { tag_key: 'supermarket-ah', display_name_nl: 'Albert Heijn', display_name_en: 'Albert Heijn', trigger_map: [{ merchant_brand: 'Albert Heijn' }] },
  { tag_key: 'supermarket-jumbo', display_name_nl: 'Jumbo', display_name_en: 'Jumbo', trigger_map: [{ merchant_brand: 'Jumbo' }] },
  { tag_key: 'supermarket-lidl', display_name_nl: 'Lidl', display_name_en: 'Lidl', trigger_map: [{ merchant_brand: 'Lidl' }] },
  { tag_key: 'drugstore', display_name_nl: 'Drogisterij', display_name_en: 'Drugstore', trigger_map: [{ merchant_brand: 'Kruidvat' }, { merchant_brand: 'Etos' }, { merchant_brand: 'Trekpleister' }] },
  { tag_key: 'variety-store', display_name_nl: 'Winkel met gevarieerd aanbod', display_name_en: 'Variety store', trigger_map: [{ merchant_brand: 'HEMA' }, { merchant_brand: 'Action' }] },
  { tag_key: 'impulse-buy', display_name_nl: 'Impulsaankoop', display_name_en: 'Impulse buy', trigger_map: [] },
  { tag_key: 'end-of-month', display_name_nl: 'Einde van de maand', display_name_en: 'End of month', trigger_map: [] },
  { tag_key: 'payday-splurge', display_name_nl: 'Salarisdag uitgave', display_name_en: 'Payday splurge', trigger_map: [] },
  { tag_key: 'budget-stretch', display_name_nl: 'Budget rekken', display_name_en: 'Budget stretch', trigger_map: [] },
  { tag_key: 'price-match', display_name_nl: 'Prijsgarantie', display_name_en: 'Price match', trigger_map: [] },
];

export default tagVocabulary;
